name: Rideshare Mileage Log
options:
  bundleIdPrefix: com.shimondeitel.rideshlog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Rideshare Mileage Log:
    type: application
    platform: iOS
    sources:
      - path: Rideshare Mileage Log
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.rideshlog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Rideshare Mileage Log/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  Rideshare Mileage LogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Rideshare Mileage LogTests
      - path: Rideshare Mileage Log.storekit
    dependencies:
      - target: Rideshare Mileage Log
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.rideshlog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  Rideshare Mileage LogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Rideshare Mileage LogUITests
    dependencies:
      - target: Rideshare Mileage Log
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.rideshlog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Rideshare Mileage Log:
    build:
      targets:
        Rideshare Mileage Log: all
        Rideshare Mileage LogTests: [test]
        Rideshare Mileage LogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Rideshare Mileage Log.storekit
    test:
      config: Debug
      storeKitConfiguration: Rideshare Mileage Log.storekit
      targets:
        - Rideshare Mileage LogTests
        - Rideshare Mileage LogUITests
    archive:
      config: Release
